#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>	//TIME FONKSIYONLARINI KULLANMAMIZ ICIN GEREKLI KUTUPHANE

FILE *dosya;	//AYNI ISIMLI DOSYA DEGISKENINI KAYBETMEMEK GLOBAL TANIMLANDI.
char fName[255];//DOSYA ISMININ HERYERDE AYNI OLMASI ICIN GLOBAL TANIMLANDI.

void findAndReplace(char text[],char find[],char replace[],int cSensitive){
	int index,j,counter=0;
	int bmt[256];
	//BAD MATCH TABLE'IN OLUSTURULMA ISLEMLERI;
	int k;
	for(k = 0; k < 256; ++k)	//TUM ASCII TABLOSUNDAKI DEGERLER KADAR DOLANIR VE HEPSINE ARANACAK METININ UZUNLUGU VERILIR,TABLO OLUSTURULUR
		bmt[k] = strlen(find);
	
	if(cSensitive==1){	//CASE SENSITIVE AKTIF DEGIL IKEN;
		for(k = 0; k < strlen(find) -1; ++k)
			bmt[find[k]] = strlen(find) - k - 1;
	}
	else{	//CASE SENSITIVE AKTIF IKEN;
		for(k = 0; k < strlen(find) -1; ++k){
			bmt[find[k]] = strlen(find) - k - 1;
			if(find[k]<=90)	//ASCII KARAKTER TABLOSUNA GORE ELDE OLAN MEVCUT SAYI BUYUK ISE;
				bmt[find[k]+32]= strlen(find) - k - 1;	//KUCUK-BUYUK HARFLERIN TABLODAKI SABIT FARKI KADAR EKLEKÝ,AYNI SAYININ KUCUK DEGERINE SAHIP OL
			else
				bmt[find[k]-32]= strlen(find) - k - 1;	//KUCUK ISE ASCII TABLOSUNDA 32 INDIS GERIYE GIDEREK AYNI KARAKTERIN BUYUGUNE SAHIP OL.
		}
	}
	//BAD MATCH TABLE'IN OLUSTURULMA ISLEMLERININ SONU.
	
	index=0;	//0 DEGERI INDISI TUTAN INDEX DEGISKENIMIZE BASLANGIC DEGERI OLARAK VERILIR
	while(index<=(strlen(text)-strlen(find))){	//INDIS DEGERI TUM TEXTIN ILE ARANAN KELIMENIN FARKINDAN KUCUK OLDUGU SURECE DEVAM ET.
												//BOYLELIKLE KONTROL ESNASINDA ARANAN KELIMENIN BOYUTUNDAN OTURU TEXT DIZISINDE TASMA OLMAZ.
  		j=strlen(find)-1;	//ARANAN KELIMENIN BIR EKSIGINI AL
  		while(((find[j]==text[index+j]) || ((fabs(find[j]-text[index+j])==fabs('Z'-'z')) && (cSensitive>0 ? 0 : 1))) && (j>=0))
    		j--;	//J DEGISKENI 1 AZALTILIR.
    	//37.SATIRDAKI WHILE:
    	//ARANAN KELIMENIN J.INDISININ TEXTIN MEVCUT INDEX + J.INDISE ESIT OLMASI DURUMU VEYA;
    	//YINE AYNI IFADENIN FARKLARININ MUTLAK DEGERLERI,ASCII TABLOSUNDA BULUNAN HERHANGI IKI HARFIN BUYUK VE KUCUK HALLERININ FARKININ MUTLAK DEGERINE ESITMI? VE;
    	//CASE SENSITIVE ICIN GIRILEN KARAR DEGISKENININ ZITTI ALINIR " (cSensitive>0 ? 0 : 1) " IFADESINDEN GELICEK OLAN 0 SONUCU BUYUK KUCUK HARF FARKINI INCELIYEN IFADEYIDE YOK EDICEGI ICIN
    	//CASE SENSITIVE OLMADAN ARAMA YAPILACAKTIR.
    	
    	//BU ANLATILAN IFADELERIN HEPSI BIR PARANTEZDE ILK IFADE(ILK OPERAND) OLARAK DUSUNDUGUMUZDE " (j>=0) " IFADESIYLE(IKINCI OPERAND) ILE ANDLENIR
    	//CUNKU J DEGISKENININ(ARANAN METIN-1 DEGERINI TUTAR) 0DAN BUYUK VEYA ESIT OLMASI GEREKLIDIR
    	//37.SATIRDAKI WHILE ACIKLAMASININ SONU.
    
  		if(j<0){//J DEGISKENININ 0IN ALTINA GIRMESI DEMEK PATTERNIN(FIND) BULUNMASI DEMEKTIR.PATTERNIN BULUNDUGU BLOK;
  			printf("\nPattern Found At Index Number=%d",index);
  			//TEXT ICIN YAPILACAK REPLACE ÝSLEMLERÝ(FIND<->REPLACE);
  			//3 DURUM OLMALIDIR;
  			
			int i;
			if(strlen(find)>strlen(replace)){	//1)BULUNAN KELIMENIN KARAKTER SAYISI DEGISECEK YENI KELIMENINKINDEN BUYUK ISE;
				
				for(i=index+strlen(replace);text[i]!='\0';i++){	//ARANAN KELIMENIN BULUNDUGU INDEX + YENI EKLENICEK KELIMENIN BOYU KADAR ILERISINDEN BASLAYIP SONUNA KADAR GIT
					text[i]=text[i+strlen(find)-strlen(replace)]; //TUM DIZIYI FARKLARI KADAR SOLA SHIFT ET.
				}
				
				for(i=0;i<strlen(replace);i++){	//YENI DEGISECEK KELIMENIN BOYUTU KADAR ILERLE
					text[index+i]=replace[i];	//PATTERNI BULDUGUN INDEX+i KADAR YENI KELIMEYI YAZ
				}
				
			}
		
			else if(strlen(find)<strlen(replace)){	//2)YENI KELIME,DEGISECEK ESKI KELIMEDEN BUYUK ISE;
				
				for(i=strlen(text);i>index;i--)	//TEXTIN EN SONUNDAN BASLAYIP PATTERNI BULDUGUMUZ INDIS DEGERINE KADAR GERI GERI GELIP DIZIMIZI SAG SHIFT EDIYORUZ.
					text[i+strlen(replace)-strlen(find)]=text[i];	//FARKLARI KADAR ILERISINDEKI INDISDEKI DEGERI=MEVCUT INDISDEKI DEGERE AT,BOYLELIKLE SAG SHIFT EDERKEN KARAKTER KAYBI YASAMAYIZ.
					
				for(i=0;i<strlen(replace);i++)	//SHIFT ISLEMINDEN SONRA HER ZAMANKI GIBI YENI KELIME MEVCUT INDISDEN ITIBAREN YAZILMAYA BASLANIR.
					text[index+i]=replace[i];	//PATTERNIN BULUNDUGU MEVCUT INDIS + I(0.1.2.3.......YENI KELIMENIN BOYUTU KADAR)DEKI DEGERLERE SIRASIYLA YENI KELIME YAZILIR.
			}
			
			else{
				for(i=0;i<strlen(replace);i++){	//3)YENI KELIME,ESKI KELIMEYLE AYNI UZUNLUGA SAHIP ISE;
					text[index+i]=replace[i];	//DIREKT OLARAK PATTERNIN BULUNDUGU INDISDEN BASLANARAK YENI KELIME YAZILIR.
				}
			}
			counter++;	//TOTAL BULUNMA VE DEGISTIRME ISLEMLERINI TUTAN DEGISKEN 1 ARTTIRILIR.
            index+=strlen(replace)+1;	//BULUNMA ISLEMLERINDEN SONRA MEVCUT INDIS DEGERININ YENI KELIMENIN 1 FAZLASI KADAR ARTTIRILMASI GEREKÝLÝR.
       
			
  		}
  		else{//INDEXIN YENIDEN BELIRLENMESI ISLEMLERI;
		    if (1>bmt[text[index+strlen(find)-1]]){	//MEVCUT INDISIMIZE ARADIGIMIZ KELIMENIN UZUNLUGUNU EKLEYIP 1 ÇIKARTMAMIZ SONUCUNDA CIKAN DEGER
													//INDIS KABUL EDILIP,TUM METININ BULUNDUGU TEXT DIZISINDE HANGI KARAKTERE GELIYOR ISE O KARAKTERIN
													//BAD MATCH TABLEIMIZDA BULUNAN(0-256 ARASI ASCII KARAKTERLERI IÇEREN) DEGERININ 1DEN BUYUK VEYA KUCUK OLMA KONTROLÜ;
       			index++;	//1DEN KUCUK ISE INDEXI 1 ARTTIR
   			}
    		else{
        		index+=bmt[text[index+strlen(find)-1]];	//1DEN BUYUK ISE INDEXI DENK GELEN IFADE KADAR ARTTIR.
    		}
        }
  		
	}
	//FIND VE REPLACE ISLEMLERIMIZ TAMAMIYLE SONA ERDI SIMDI SIRA TEKRAR DOSYAMIZA YAZMADA;
	int a=0;
	dosya=fopen(fName,"w");	//AYNI DOSYA ISMINI WRITE MODU ILE ACIYORUZ.
	while(text[a]!='\0'){	//TEXTIN SONUNA GELENE KADAR;
		fputc(text[a],dosya);	//KARAKTER KARAKTER DOSYAYA KOY
		a++;
	}
	fclose(dosya);	//DOSYAYI KAPAT
	
	printf("\nNew Text:%s\nFound And Replaced:%d",text,counter);	//TEXTIN SON HALINI,FOUND VE REPLACE SAYILARINI YAZDIRARAK FONKSIYONU SONA ERDIR.
}

int main(){
  	char find[255],replace[255],text[25500];
	int cSensitive;
	struct timespec start;	//CLOCK SAYIMI YAPICAGIMIZ ICIN SURE KAYDININ BASLANGIC DEGERINI TUTMAK ICIN OLUSTURDUGUMUZ STRUCT TIPINDEKI DEGISKENIMIZ.
	struct timespec finish;	//AYNI SEKILDE CLOCK SAYIMI BITTIKTEN SONRAKI KAYIT SONU DEGERINI TUTUCAK OLAN DEGISKENIMIZ.
	
	printf("FIND:");
	gets(find);
	printf("REPLACE:");
	gets(replace);
	printf("Enter The FILE Name(.txt Format):");
	gets(fName);//GLOBAN TANIMLANDI BOYLELIKLE FONKSIYON ICERISINDE RAHATLIKLA ISMI GECTIGI YERDEN ERISILEBILECEK.
	
	printf("Is This A Case Sensitive Searching? (YES=1	NO=0):");
	scanf("%d",&cSensitive);
	
	if(cSensitive==1||cSensitive==0){
		//DOSYADAKI METININ ALINMASI ISLEMI
		int i=0;
		dosya=fopen(fName,"r");	//VERILEN DOSYA ISMINDE DOSYA READ MODU ILE ACILIR
		while(!feof(dosya)){	//DOSYANIN SONUNA GELENE KADAR;
			fscanf(dosya,"%c",&text[i]);	//KARAKTER KARAKTER OKU,TEXT DIZISINE AT(TUM METIN TEXT DIZISINDE TUTULUR)
			i++;
		}
		fclose(dosya);//DOSYA KAPATILIR.
		//DOSYADAKI METIN ALINDI text ISIMLI DIZIYE ATILDI.
		printf("Text=%s	\nFind:%s     <-->     Replace With:%s\n",text,find,replace);

		clock_gettime(CLOCK_MONOTONIC,&start);	//clock_gettime FONKSIYONU ILE SUREYI ANLIK YAKALAR VE start DEGISKENINE ATAR.
		findAndReplace(text,find,replace,cSensitive);	//***ASIL FONKSIYONUMUZ
		clock_gettime(CLOCK_MONOTONIC,&finish);	//IKINCI SUREYI YAKALARIZ VE finish DEGISKENINE ATARIZ
		//GEREKLI DONUSUMLER YAPILIP MILI SANIYE CINSINDEN EKRANA YAZDIRILIR,SON ALDIGIMIZ ZAMAN KAYDINDAN ILK ALDIGIMIZ ZAMAN KAYDINI CIKARTIRIZ(finish-start)
		printf("\nOperation Took: %lf miliseconds", (double)((long int)(finish.tv_sec-start.tv_sec)*1000000000 + (finish.tv_nsec-start.tv_nsec))/1000000);
		
		
  	}
  		
  	else
  		printf("Type Just 1 Or 0 For Case Sensitive Decision...");
  	
 	return 0;
}
